[package]
name = "tari_comms"
description = "A peer-to-peer messaging system"
repository = "https://github.com/tari-project/tari"
homepage = "https://tari.com"
readme = "README.md"
license = "BSD-3-Clause"
version = "0.0.5"
edition = "2018"

[features]
next = ["yamux", "snow"]

[dependencies]
tari_crypto = { version="^0.0",  path = "../infrastructure/crypto" }
tari_storage = { version="^0.0", path = "../infrastructure/storage" }
tari_utilities = { version="^0.0",  path = "../infrastructure/tari_util" }
tari_shutdown = { version="^0.0",  path = "../infrastructure/shutdown" }

bitflags = "1.0.4"
bytes = "0.4.12"
chrono = { version = "0.4.6", features = ["serde"] }
clear_on_drop = "0.2.3"
derive-error = "0.0.4"
digest = "0.8.0"
futures =  { version = "^0.3", features = ["async-await"]}
lazy_static = "1.3.0"
lmdb-zero = "0.4.4"
log = { version = "0.4.0", features = ["std"] }
multiaddr = {version = "0.7.0", package = "parity-multiaddr"}
prost = "0.5.0"
rand = "0.5.5"
serde = "1.0.90"
serde_derive = "1.0.90"
serde_repr = "0.1.5"
snow = {version="0.6.2", path="./snow", features=["default-resolver"], optional = true}
time = "0.1.42"
tokio = {version="^0.2", features=["blocking", "tcp", "stream", "dns"]}
ttl_cache = "0.5.1"
yamux = {version="0.4.0", optional = true}
zmq = "0.9.2"

[dev-dependencies]
tari_test_utils = {path="../infrastructure/test_utils"}

criterion = "0.2"
env_logger = "0.7.0"
futures-test = { version = "0.3.0-alpha.19", package = "futures-test-preview" }
rand = "0.5.5"
serde_json = "1.0.39"
tari_common = { path = "../common", version = "^0.0" }
tokio-mock-task = "0.1.1"
tokio-macros = "0.2.3"

[build-dependencies]
tari_protobuf_build = { version = "^0.0", path="../infrastructure/protobuf_build"}
